#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Nov 28 19:17:54 CST 2022
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 80ff0a00a9d0446d87486edbbcdfd74d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot RISC_SIMULATION_behav xil_defaultlib.RISC_SIMULATION -log elaborate.log"
xelab -wto 80ff0a00a9d0446d87486edbbcdfd74d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot RISC_SIMULATION_behav xil_defaultlib.RISC_SIMULATION -log elaborate.log

